% Compute spectrogram

% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 10-Oct-2022 19:45:34
%%
% Parameters
frequencyLimits = [0 1]; % Normalized frequency (*pi rad/sample)
overlapPercent = 50;

%%
% Index into signal time region of interest
timeLimits = [1 9000]; % samples
smcAC_2_ROI = smcAC_2(:);
smcAC_2_ROI = smcAC_2_ROI(timeLimits(1):timeLimits(2));

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[P,F,T] = pspectrum(smcAC_2_ROI, ...
    'spectrogram', ...
    'FrequencyLimits',frequencyLimits, ...
    'OverlapPercent',overlapPercent);
